sudo: required
language: python
matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python3 -m pip install --upgrade pip wheel
    - python: "2.7"
      dist: xenial
    - python: "3.4"
      dist: trusty
    - python: "3.5"
      dist: xenial
    - python: "3.6"
      dist: xenial
    - python: "3.7"
      dist: xenial
    - python: "3.8-dev"
      dist: xenial
    - python: "pypy"
      dist: trusty
    - python: "pypy3"
      dist: trusty
  allow_failures:
    - python: "3.8-dev"
    - python: "pypy"
    - python: "pypy3"
cache: pip
script:
  - make travis
